[package]
name = "esm-cjs-lexer"
version = "0.7.0"
description = "A WASM module to parse commonjs exports for ESM."
repository = "https://github.com/ije/esm.sh"
license = "MIT"
authors = ["The Aleph.js authors"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.57"
indexmap = "1.8.2"
serde = { version = "1.0.137", features = ["derive"] }

# swc
# docs: https://swc.rs
# crate: https://crates.io/search?q=swc
swc_common = { version = "0.15.3", features = ["sourcemap"] }
swc_ecmascript = { version = "0.102.0", features = ["parser", "visit"] }
swc_ecma_ast = "0.61.0"
swc_ecma_visit = "0.47.0"

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.80", features = ["serde-serialize"]}
console_error_panic_hook = { version = "0.1.7", optional = true }

[profile.release]
# Tell `rustc` to optimize for speed and size
lto = true
